import { Component } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { HeaderComponent } from '../header/header.component';
import { LanguageService } from '../../service/language.service';
import { FooterComponent } from "../footer/footer.component";

@Component({
  selector: 'app-privacy-policy',
  standalone: true,
  imports: [
    HeaderComponent,
    RouterLink,
    FooterComponent
],
  templateUrl: './privacy-policy.component.html',
  styleUrl: './privacy-policy.component.scss'
})
export class PrivacyPolicyComponent {
  constructor(
    private router: Router,
    private languageService: LanguageService) {}

  privacyPolicy: {
    title: string;
    lastUpdated: string;
    tableOfContents: string;
    overviewOfProcessingOperations: string;
    applicableLegalBases: string;
    securityMeasures: string;
    transferOfPersonalData: string;
    internationalDataTransfer: string;
    dataStorage: string;
    rightsOfDataSubjects: string;
    businessServices: string;
    provisionOfOnlineServices: string;
    useOfCookies: string;
    contactAndRequestManagement: string;
    personResponsible: string;
    overviewOfProcessingText1: string;
    overviewOfProcessingText2: string;
    inventoryData: string;
    paymentData: string;
    contactData: string;
    contentData: string;
    contractData: string;
    usageData: string;
    meta: string;
    logData: string;
    categoriesOfDataSubjects: string;
    recipientsOfServicesAndContractingParties: string;
    interestedParties: string;
    communicatingPartners: string;
    users: string;
    businessAndContractualPartners: string;
    purposesOfProcessing: string;
    provisionOfContractualServices: string;
    communication: string;
    office: string;
    organization: string;
    feedback: string;
    provisionOfServices: string;
    infrastructure: string;
    economic: string;
    applicableLegalBasesUnderGDPR: string;
    applicableLegalBasesUnderGDPRText: string;
    consent: string;
    consentText: string;
    contract: string;
    contractText: string;
    legalObligation: string;
    legalObligationText: string;
    legalInterest: string;
    legalInterestText: string;
    nationalDataProtectionRegulations: string;
    nationalDataProtectionRegulationsText: string;
    swissFADP: string;
    swissFADPText: string;
    securityMeasuresText1: string;
    securityMeasuresText2: string;
    transferOfPersonalDataText: string;
    generalInformation: string;
    generalInformationText1: string;
    generalInformationText2: string;
    generalInformationText3: string;
    generalInformationText4: string;
    generalInformationText5: string;
    generalInformationText6: string;
    furtherNotes: string;
    retentionAndDeletion: string;
    retentionAndDeletionText: string;
    retentionAndDeletion10Years: string;
    retentionAndDeletion6Years: string;
    retentionAndDeletion3Years: string;
    rightsOfDataSubjectsText: string;
    rightToObject: string;
    rightToObjectText: string;
    rightToWithdraw: string;
    rightToWithdrawText: string;
    rightToAccess: string;
    rightToAccessText: string;
    rightToErasure: string;
    rightToErasureText: string;
    rightToRectification: string;
    rightToRectificationText: string;
    rightToDataPortability: string;
    rightToDataPortabilityText: string;
    rightToLodgeComplaint: string;
    rightToLodgeComplaintText: string;
    businessServicesText1: string;
    businessServicesText2: string;
    businessServicesText3: string;
    businessServicesText4: string;
    processedDataTypes: string;
    businessProcessedDataTypesText: string;
    affectedPersons: string;
    businessAffectedPersonsText: string;
    businessPurposesOfProcessing: string;
    businessPurposesOfProcessingText: string;
    businessRetentionAndDeletion: string;
    businessRetentionAndDeletionText: string;
    legalBases: string;
    businessLegalBasesText: string;
    onlineShop: string;
    onlineShopText: string;
    onlineShopLegalBases: string;
    onlineShopLegalBasesText: string;
    provisionOfOnlineServicesAndWebhosting: string;
    provisionOfOnlineServicesAndWebhostingText: string;
    provisionOfOnlineServicesText: string;
    provisionProcessedDataTypesText: string;
    provisionAffectedPersonsText: string;
    provisionPurposesOfProcessing: string;
    provisionPurposesOfProcessingText: string;
    provisionRetentionAndDeletion: string;
    provisionRetentionAndDeletionText: string;
    provisionLegalBasesText: string;
    collectionOfAccessData: string;
    collectionOfAccessDataText: string;
    collectionOfAccessDataLegalBasis: string;
    collectionOfAccessDataLegalBasisText: string;
    collectionOfAccessDataDataDeletion: string;
    collectionOfAccessDataDataDeletionText: string;
    useOfCookiesText: string;
    useOfCookiesNotesOnLegalBases: string;
    useOfCookiesNotesOnLegalBasesText: string;
    useOfCookiesRetention: string;
    useOfCookiesRetentionText: string;
    useOfCookiesTemporaryCookies: string;
    useOfCookiesTemporaryCookiesText: string;
    useOfCookiesPermanentCookies: string;
    useOfCookiesPermanentCookiesText: string;
    useOfCookiesOptOut: string;
    useOfCookiesOptOutText: string;
    useOfCookiesProcessedDataTypesText: string;
    useOfCookiesAffectedPersonsText: string;
    useOfCookiesLegalBasesText: string;
    furtherNotesOnProcessingActivitiesAndProcedures: string;

  } = {
    title: '',
    lastUpdated: '',
    tableOfContents: '',
    overviewOfProcessingOperations: '',
    applicableLegalBases: '',
    securityMeasures: '',
    transferOfPersonalData: '',
    internationalDataTransfer: '',
    dataStorage: '',
    rightsOfDataSubjects: '',
    businessServices: '',
    provisionOfOnlineServices: '',
    useOfCookies: '',
    contactAndRequestManagement: '',
    personResponsible: '',
    overviewOfProcessingText1: '',
    overviewOfProcessingText2: '',
    inventoryData: '',
    paymentData: '',
    contactData: '',
    contentData: '',
    contractData: '',
    usageData: '',
    meta: '',
    logData: '',
    categoriesOfDataSubjects: '',
    recipientsOfServicesAndContractingParties: '',
    interestedParties: '',
    communicatingPartners: '',
    users: '',
    businessAndContractualPartners: '',
    purposesOfProcessing: '',
    provisionOfContractualServices: '',
    communication: '',
    office: '',
    organization: '',
    feedback: '',
    provisionOfServices: '',
    infrastructure: '',
    economic: '',
    applicableLegalBasesUnderGDPR: '',
    applicableLegalBasesUnderGDPRText: '',
    consent: '',
    consentText: '',
    contract: '',
    contractText: '',
    legalObligation: '',
    legalObligationText: '',
    legalInterest: '',
    legalInterestText: '',
    nationalDataProtectionRegulations: '',
    nationalDataProtectionRegulationsText: '',
    swissFADP: '',
    swissFADPText: '',
    securityMeasuresText1: '',
    securityMeasuresText2: '',
    transferOfPersonalDataText: '',
    generalInformation: '',
    generalInformationText1: '',
    generalInformationText2: '',
    generalInformationText3: '',
    generalInformationText4: '',
    generalInformationText5: '',
    generalInformationText6: '',
    furtherNotes: '',
    retentionAndDeletion: '',
    retentionAndDeletionText: '',
    retentionAndDeletion10Years: '',
    retentionAndDeletion6Years: '',
    retentionAndDeletion3Years: '',
    rightsOfDataSubjectsText: '',
    rightToObject: '',
    rightToObjectText: '',
    rightToWithdraw: '',
    rightToWithdrawText: '',
    rightToAccess: '',
    rightToAccessText: '',
    rightToErasure: '',
    rightToErasureText: '',
    rightToRectification: '',
    rightToRectificationText: '',
    rightToDataPortability: '',
    rightToDataPortabilityText: '',
    rightToLodgeComplaint: '',
    rightToLodgeComplaintText: '',
    businessServicesText1: '',
    businessServicesText2: '',
    businessServicesText3: '',
    businessServicesText4: '',
    processedDataTypes: '',
    businessProcessedDataTypesText: '',
    affectedPersons: '',
    businessAffectedPersonsText: '',
    businessPurposesOfProcessing: '',
    businessPurposesOfProcessingText: '',
    businessRetentionAndDeletion: '',
    businessRetentionAndDeletionText: '',
    legalBases: '',
    businessLegalBasesText: '',
    onlineShop: '',
    onlineShopText: '',
    onlineShopLegalBases: '',
    onlineShopLegalBasesText: '',
    provisionOfOnlineServicesAndWebhosting: '',
    provisionOfOnlineServicesAndWebhostingText: '',
    provisionOfOnlineServicesText: '',
    provisionProcessedDataTypesText: '',
    provisionAffectedPersonsText: '',
    provisionPurposesOfProcessing: '',
    provisionPurposesOfProcessingText: '',
    provisionRetentionAndDeletion: '',
    provisionRetentionAndDeletionText: '',
    provisionLegalBasesText: '',
    collectionOfAccessData: '',
    collectionOfAccessDataText: '',
    collectionOfAccessDataLegalBasis: '',
    collectionOfAccessDataLegalBasisText: '',
    collectionOfAccessDataDataDeletion: '',
    collectionOfAccessDataDataDeletionText: '',
    useOfCookiesText: '',
    useOfCookiesNotesOnLegalBases: '',
    useOfCookiesNotesOnLegalBasesText: '',
    useOfCookiesRetention: '',
    useOfCookiesRetentionText: '',
    useOfCookiesTemporaryCookies: '',
    useOfCookiesTemporaryCookiesText: '',
    useOfCookiesPermanentCookies: '',
    useOfCookiesPermanentCookiesText: '',
    useOfCookiesOptOut: '',
    useOfCookiesOptOutText: '',
    useOfCookiesProcessedDataTypesText: '',
    useOfCookiesAffectedPersonsText: '',
    useOfCookiesLegalBasesText: '',
    furtherNotesOnProcessingActivitiesAndProcedures: '',
  }

  ngOnInit() {
    this.languageService.language$.subscribe(lang => {
      this.languageService.translateLanguage(this.privacyPolicy, 'privacyPolicy');
    });
  }
}
